# Generated by Django 4.2.1 on 2023-05-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClosestPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_set", models.CharField(max_length=255)),
                ("closest_points", models.CharField(max_length=255)),
            ],
        ),
    ]
